name: Web Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: release
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: |
            captain-definition
            package.json
            Dockerfile
            index.html
            styles.css
          outPath: deploy.tar
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.WEB_APP_NAME }}"
          token: "${{ secrets.WEB_APP_TOKEN }}"
